spring:
  application:
    name: sf-movies
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./moviesdb;TRACE_LEVEL_FILE=3
    username: root
    password: root
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

server:
  port: 8088

app:
  basePackage: "org.amrit.sfmovies"
  basePath: "/api.*"

client:
  url: "https://sf-movies-frontend.herokuapp.com"